app-config:
  host: 192.168.141.176
  progId: KingView.View.1
  user: Administrator
  password: 123456
  #PLC编号映射
  plcNumberDictionary:
    6010403001: 111
    6010403002: 112
    6010403003: 113
    6010403004: 114
    6010402001: 115


server:
  # WebServer bind port
  port: 9011
  tomcat:
    uri-encoding: UTF-8
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
security:
  jwt:
    login:
      username: OpcAdmin
      password: SummitOpcAdmin
    token:
      secret-key: secret-key
      #单位小时
      expire-length: 24

