app-config:
  host: 192.168.141.176
  progId: KingView.View.1
  user: Administrator
  password: 123456
  #PLC编号映射
  plcNumberDictionary:
    767671: 111
#    767672: 112
#    767673: 113
#    767679: 114
#    767678: 115


server:
  # WebServer bind port
  port: 9011
security:
  jwt:
    login:
      username: admin
      password: 123456
    token:
      secret-key: secret-key
      expire-length: 36000